### ISSUE TITLE
Conda package?

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [noaa-ocs-s100/s100py#10]
I note in your docs:

"""
This package requires the GDAL Python bindings be present, so it usually can't just be installed using pip install gdal. We recommend installing GDAL either through a package manager (e.g. conda, apt, yum, pacman) or by compiling from scratch. [Miniconda](https://docs.conda.io/en/latest/miniconda.html) is probably the easiest method.
"""
It seems it would be helpful to your users to make a conda package available for s100py itself, so folks could simply do

`conda install -c conda-forge s100py`

It would be pretty straightforward to add a new conda-forge "feedstock", and once in, it's pretty self maintaining.

Let me know if you want some help -- we've done a fair bit of this to support NOAA / ORR projects, notably PyGNOME.

HMM -- it looks like there hasn't been an update it a while -- maybe this could wait 'till the next release.

(https://github.com/NOAA-ORR-ERD/PyGnome)

**Comment by barry-gallagher** [comment]
Hi @ChrisBarker-NOAA  

We will probably take you up on some help on creating a Conda feedstock.  We are currently updating for S100 v5.0 and S102 v2.2 in a branch.  The last update for S100 v4.0 and S102 v2.0 + v2.1 are actually in the dev branch.  We planned to move everything into main/master but the S104 and S111 didn't get finished at the time.  

As part of this update cycle I'd like to make a Conda install (that's what I normally use) since the person that wrote that comment and made the pip install script is no longer with NOAA anyway.  I've been intending for years to get more familiar with creating conda packages rather than just using it for installing, so your timing is perfect.

**Comment by ChrisBarker-NOAA** [comment]
Ah -- I see where the active development is now.

Sound like it makes sense to do a conda package when you get the new version released.

Give me a ping when it's ready, I'm happy to help.

Side note: This might be a good time to modernize your build setup -- an active setup.py is now deprecated. You can go to `setup.cfg` pretty easily, or almost as easily, pyproject.toml:

https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html

**Comment by barry-gallagher** [comment]
Hi @ChrisBarker-NOAA 

We starting work on submitting to conda-forge, so you may get questions from us shortly.  We have another colleague that just got conda-forge approval which he said took a month before the review happened.  Also, we are hopeful that GDAL will supply read-only support for gridded arrays (data coding format 2) soon for both v2.1 and then v2.2 (added feature attribute tables) for S102.

**Comment by ChrisBarker-NOAA** [comment]
Good to know -- one note: I don't see a release since 2021 -- it's best to first make a release on gitHub, and then the conda package can be built from that (or from PyPi if you push there).

>  took a month before the review happened

Hmm -- I've had better luck recently, but we'll see -- conda-forge is under-staffed (under-volunteered?)

**Comment by erin-nagel** [comment]
@ChrisBarker-NOAA s100py is now available on Conda
